id: AC22CDF8F
title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s Teachings
  in Tibet'
type: translation
pechas:
- ID7F3430F
- I5AE25E9E
- IBA488958
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:41.584071
  last_modified_at: 2023-01-04 12:33:41.584086
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  ID7F3430F/FBAD: 1D91
  I5AE25E9E/199B: 1D91
  IBA488958/FFC8: 1D91
